### ISSUE TITLE
Issues on utilization

### ISSUE THREAD

**Issue by New-MX** [oubaydos/flipsnack-to-pdf#1]
Hello,

First i apologize if the question is easy for you, but I'm not a developer 
So I would like to use it on Ubuntu. But I have some issues on utilization with the Chromium lib or with Brave. 
See bellow with a test book and the chromium lib in the Python Script :
![image](https://user-images.githubusercontent.com/50262916/141656898-0cf680aa-9a54-4fdc-a20b-07f77432d128.png)

See bellow with the salme test book and Brave in the Python Script :
![image](https://user-images.githubusercontent.com/50262916/141657531-83721e54-4ed4-4d3e-b0dc-1eeb27054d31.png)

Do you have a process, for how to use it (or install, maybe) ?
Which OS do you use by default ?

Spend 30 buck, for a homework is a little too much... :P

Thank

Regards,
Mx

**Comment by oubaydos** [comment]
thanks for opening this issue. it seems that selenium couldnt find a certain element on the page of the book. can you give the link of the book you are trying to downlad ? to see if i could regenerate the problem.
To answer your questions; i use ubuntu and brave. i will add a documentation in the next days !
Thanks Mr MX.
Oubaydos

**Comment by New-MX** [comment]
Hey,
Thank for the quick answer.
I had many problems in installing the Selenium library, (the dependency and pip3...). Or is maybe my installation of Brave which is not complete ?
This is a link of a test FlipBook : [TestFlipBook](https://www.flipsnack.com/splandidmen2/testfb.html) [https://www.flipsnack.com/splandidmen2/testfb.html]

Thank for the further documentation :)

Have a nice day :)
Mx

**Comment by oubaydos** [comment]
hello, i was able to generate the bug: it was because i setted up my script to work with books like this [example](https://www.flipsnack.com/gsmaworld/the-enablement-effect-report.html), and the problem was that my script was trying to locate the button "fullscreen" in the middle of the screen, but couldnt find it in your book, because it was in the bottom right part of the screen with a different html id/class. I will try to solve this issue when i have time! 
Thanks for your comments.
I am sorry i couldnt help you getting the pdf you wanted.
You may close the issue now.
oubaydos

**Comment by New-MX** [comment]
> "I am sorry i couldnt help you getting the pdf you wanted."

 It's ok, no problem. You are the only one to do this and to share it so thank for this :D

Update1 : 
I was able to have the "fullscreen" button :
First you need to go in "Flipbooks" (1) and go to "Customize" (2).
![image](https://user-images.githubusercontent.com/50262916/141694145-4e1fda11-89b5-4936-b746-48e3d3bc0931.png)
On the next page go in "Appearance & branding" (3), change "Modern" to "Classic" (4). Finally reupload the book "Save and Share" (5) :)
![image](https://user-images.githubusercontent.com/50262916/141694301-e878bdec-5589-4396-8ac0-2887fc584cc9.png)
Result : 
![image](https://user-images.githubusercontent.com/50262916/141694396-e519a484-a8e7-405e-9809-6626de39ad0b.png)

I think I have badly installed Brave, because I need to use Chromium browser to make it work. Also, my PDF is empty.
Well, I will wait now (and continue to look). 

Thank  :D

++
Mx

**Comment by oubaydos** [comment]
hello, so i have looked up the problem again, and i found that the way this pdf was generated in flipsnack ( it contains gifs ... ) so the script will not be able to convert it to pdf. i will try to work on this feature in the next weeks. 
But for now the script can only handle a book that was a pdf /word... in the first place and was converted to a flipsnack book.
Thanks
