### ISSUE TITLE
Don't know how to format the path to Chromium browser

### ISSUE THREAD

**Issue by Rozelda** [oubaydos/flipsnack-to-pdf#3]
Hi!

Thank you for the project!

I am not a programmer and don't know how to format the path to the Chromium browser version 92 I installed specifically for this project. When I click enter after entering the path the python terminal closes automatically without anything happening:

![Screenshot 2022-01-02 200050](https://user-images.githubusercontent.com/23418572/147893856-865af24b-6bbb-4e59-9590-0ba0fd523765.png)

Thanks in advance for your help.

**Comment by oubaydos** [comment]
hello, there has been some problems with my script the last days, and it will not work eitherway (because of some dependencies incompatibilities), so i will try to "dockerize" it, so it can be portable, and working on every platform.
I am sorry for the inconvenience, it's just that i dont have much free time these days.
I will try to solve the issues.
Thanks for your issue,
Obaydah

**Comment by Rozelda** [comment]
Thanks for the reply Oubaydos. 

Would using Brave solve the issue? (I'm on Windows 10).

**Comment by luukmvb** [comment]
i've been trying to do this for days. can some one convert it to pdf and send it via mail pls.

https://www.flipsnack.com/B6BB5899E8C/woonstijlen.html

mail: 2007359@leerling.vhl.nl

**Comment by oubaydos** [comment]
@Rozelda no it wont, this is a problem i ve been having my self.

**Comment by oubaydos** [comment]
@luukmvb it's just that this is the midterm exams and i really have no time to fix the issue, 
however i will try when possible to work on it.
one last thing, as i checked the pdf you want to convert, i found that it was generated in flipsnack and was not originally a pdf/word .., and for that my script wont be working as mentionned in ReadMe file.
Thanks.
Obaydah

**Comment by Rozelda** [comment]
Dear Oubaydos,

I hope your midterm exams went well. I was wondering by any chance if you had an opportunity to make progress on the issue with the code? Looking forward to hear from you!

**Comment by cyhonik** [comment]
Hi @oubaydos, thanks for the sharing the documentatio. I've followed your guidance and use the script but got below result:
  File "index.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

By any chance you know how to solve this issue? thanks.

**Comment by oubaydos** [comment]
hello @Rozelda 
i am sorry for the late reply of my side.
as for the problem, i was able to fix it in my ubuntu, however the dependency is still reproduceable,  in other os.
and i am still trying to figure out how to solve it.
try to download this version of brave : [brave 1.27.106](https://github.com/brave/brave-browser/releases/download/v1.27.106/brave-browser_1.27.106_amd64.deb)
and these dependencies : 

- pip install selenium==4.1.0
- pip install validators==0.18.2
- pip install fpdf==1.7.2

and try again

@cyhonik try doing the same thing ( and use linux )

**Comment by Rozelda** [comment]
Hello @oubaydos and thank you for your reply.

I installed the recommended version of Brave (in Windows 10)  as well as the dependencies.

Unfortunately, I still receive the same error message as initially. ("please enter the path of the chromium based driver /version 92"

Best regards,

Rozelda

**Comment by Rozelda** [comment]
Hello Oubaydos,

I was wondering if there is any progress on fixing the issue?

Thank you!

**Comment by lorenzolangone** [comment]
i have the same message "please enter the path of the chromium based driver /version 92"
