### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Emilyaugustt** [oubaydos/flipsnack-to-pdf#4]
Hi, so im not a developer i really don't get how to use, can u explain from the beginning? Sorry

**Comment by AwesomeKung** [comment]
Same here I already install selenium and everything but i don't know where to paste link. When I paste link on IDLE SHELL it cause error: SyntaxError: invalid decimal literal
What to do? I want to get a pdf from this link:
https://www.recursos.altamar.es/recursos/teacher/87dc0e7702875f8a199ae56be9a52b76e26dbf84/37fdf9ff3c1dbec7d70fd90d61db664639113c16
